name: PlatformIO CI

on: [push]

jobs:
  build:

    runs-on: greenpi

    steps:
    - uses: actions/checkout@v2
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Cache PlatformIO
      uses: actions/cache@v2
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: Run PlatformIO
      run: /home/pi/.local/bin/pio run
    - name: Run PlatformIO Test
      run: /home/pi/.local/bin/pio test -e native
    - name: Run Upload
      run: /home/pi/.local/bin/pio run --target upload
