name: PlatformIO CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: infinitecoding/platformio-for-ci:5.0.3
    steps:
    - uses: actions/checkout@v2
    - name: PlatformIO Run
      run: pio run
    - name: PlatformIO Test
      run: pio test -e native > test.output
    - name: Convert test results
      if: always()
      run: python ./_deploy/TestResultsParser.py test.output test.xml
    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: test-results
        path: test.xml
    - name: List files
      run: ls -la
    - name: Publish test results
      uses: MirrorNG/nunit-reporter@v1.0.5
      if: always()
      with:
        path: '*test.xml'
        access-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Cleanup test results
      if: always()
      run: rm test.output && rm test.xml

  deploy:
    runs-on: greenpi
    needs: [build]
    steps:
    - uses: actions/checkout@v2
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Cache PlatformIO
      uses: actions/cache@v2
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: PlatformIO Upload
      run: /home/pi/.local/bin/pio run --target upload
